// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Web OAuth client ID — required for Firebase Google Sign-In on Android.
  static const String googleWebClientId =
      '828546254721-4ift6ifbjdcv10bt3lt5uvn1e9d9r19p.apps.googleusercontent.com';

  /// Debug SHA-1 for this machine — add in Firebase Console → Android app → fingerprints.
  static const String androidDebugSha1 =
      '13:F9:28:16:FD:0F:88:8B:23:55:D6:82:46:4B:A7:97:14:0F:65:78';

  /// iOS OAuth client ID from Firebase / Google Cloud.
  static const String googleIosClientId =
      '828546254721-bdb4fju79irp14cvbc2oto7mdnl1ga3f.apps.googleusercontent.com';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA97xmTSexLB_OM4FLNU9Utb7aD4NEB3Lk',
    appId: '1:828546254721:web:9b2ac4bbf3753746eeca80',
    messagingSenderId: '828546254721',
    projectId: 'mtag-41516',
    authDomain: 'mtag-41516.firebaseapp.com',
    storageBucket: 'mtag-41516.firebasestorage.app',
    measurementId: 'G-LKTD8MTRJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtfD8mrIJxtbbNGrAmkkokIPJyIOSMtK4',
    appId: '1:828546254721:android:4331c9140be2de24eeca80',
    messagingSenderId: '828546254721',
    projectId: 'mtag-41516',
    storageBucket: 'mtag-41516.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaprAWpXR1BCyLDGKyflUgh87wMlbX4ug',
    appId: '1:828546254721:ios:5152ea8805c272adeeca80',
    messagingSenderId: '828546254721',
    projectId: 'mtag-41516',
    storageBucket: 'mtag-41516.firebasestorage.app',
    iosBundleId: 'com.example.mtagQueueSkipper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaprAWpXR1BCyLDGKyflUgh87wMlbX4ug',
    appId: '1:828546254721:ios:5152ea8805c272adeeca80',
    messagingSenderId: '828546254721',
    projectId: 'mtag-41516',
    storageBucket: 'mtag-41516.firebasestorage.app',
    iosBundleId: 'com.example.mtagQueueSkipper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA97xmTSexLB_OM4FLNU9Utb7aD4NEB3Lk',
    appId: '1:828546254721:web:ccaa8289d7098ecaeeca80',
    messagingSenderId: '828546254721',
    projectId: 'mtag-41516',
    authDomain: 'mtag-41516.firebaseapp.com',
    storageBucket: 'mtag-41516.firebasestorage.app',
    measurementId: 'G-FB3BHZJ43C',
  );
}
